package com.jxkj.fit_5a.lanya;

import java.util.ArrayList;


// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

/**
 * @author shenbiao
 * @date 2018/8/15
 */
public class DataManage {

	private byte mStart;
	private byte mMessage;
	private byte mClientId;
	private byte mMeterId;
	private ArrayList<Integer> mDataPayload;
	private byte mChecksum;


	/**
	 * 只用于处理接收的数据
	 * @param bytes
	 *
	 */
	public DataManage(byte[] bytes) {
		if(bytes.length > 5){
			newMessage(bytes);
		}
	}

	private void newMessage(byte[] bytes) {
		mStart = bytes[0];
		mMessage = bytes[1];
		mClientId = bytes[2];
		mMeterId = bytes[3];
		mDataPayload = getDataPayloadbytes(bytes);
		mChecksum = bytes[bytes.length-1];
	}

	private ArrayList<Integer> getDataPayloadbytes(byte[] bytes) {
		if(bytes.length<=5){
			return null;
		}
		int startPos = 4;
		int endPos = bytes.length-1;
		ArrayList<Integer> mDataNew = new ArrayList<>();
		for(int i=startPos;i<endPos;i++){
			if((ConstValues_Ly.METER_ID==ConstValues_Ly.METER_ID_S[0] || ConstValues_Ly.METER_ID==ConstValues_Ly.METER_ID_S[3])  || ConstValues_Ly.METER_ID==ConstValues_Ly.METER_ID_S[4]){
				mDataNew.add(bytes[i]-1);
			}else if(ConstValues_Ly.METER_ID==ConstValues_Ly.METER_ID_S[1] || ConstValues_Ly.METER_ID==ConstValues_Ly.METER_ID_S[2]){
				mDataNew.add((int) bytes[i]);
			}
		}
		return mDataNew;
	}

	public byte getStart() {
		return mStart;
	}

	public byte getMessage() {
		return mMessage;
	}

	public byte getClientId() {
		return mClientId;
	}

	public byte getMeterId() {
		return mMeterId;
	}

	public ArrayList<Integer> getDataPayload() {
		return mDataPayload;
	}

	public byte getChecksum() {
		return mChecksum;
	}
}
